[package]
name = "timesheet"
version = "0.1.0"
authors = ["Tommy Joe Lund <tomlun92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
dirs = "3.0.1"
rusqlite = "0.24.2"
